### ISSUE TITLE
Organize Resources

### ISSUE THREAD

**Issue by ghost** [devclokoja/resources#5]
The resources look clustered all together. It will be nice an well-organized grouping each Category to Language/Framework specific resource and guides.

**Example:**
- **Web/Mobile Development**
- **JavaScript**
  - Courses
  - Tutorials 
  ...
- **CSS**
  - Courses
  - Tutorials
  ...
- **Dart/Flutter**
  - Courses
  - Tutorials
  ...

**Comment by BolajiAyodeji** [comment]
Thanks for this amazing suggestion @sarscode !

The thing is we don't want to have framework-specific resources, it will make the resource bulky and we want it minimal. So we want just max of 10 full resources per category.

If we want to have resources for every framework needed in web development, we'll have to cover all in front-end, backend and all. That would be a lot.

We can maybe make it just one bullet under each sub (so it's courses + tutorials together)

We need to make this high recommendation and very little. What do you think?

**Comment by BolajiAyodeji** [comment]
Let's focus more on full-stack courses that'll cover most items in each category.

Full web dev courses, full mobile dev, full UI/UX and so on.

Let's iterate the list now with this.

**Comment by ghost** [comment]
As you suggested, it's fine having all the resources together, so it doesn't get too bulky.

**Comment by BolajiAyodeji** [comment]
I've made some changes @sarscode, it looks more minimal and not too clustered.
 What do you think?

**Comment by ghost** [comment]
Awesome!!! @BolajiAyodeji  I think this is cool and makes it easy for anyone to jump to a section and locate resources instead of having to look through several sections just to get a resource on a particular category.

**Comment by BolajiAyodeji** [comment]
Thank you for raising this issue. I'll be closing now :)
